"use client";

import { FormEvent, useMemo, useState } from "react";
import { CheckCircle2, CircleAlert, Users } from "lucide-react";
import styles from "./GovernancePanel.module.css";

export type GovernanceWorkspace = { workspace_id: string; name: string; owner_id?: string; checklist?: { complete: boolean; missing: string[] } };
export type GovernanceMember = { member_id: string; workspace_id: string; role: string; status: string };
export type GovernanceAudit = { timestamp?: string; actor_id?: string; project_id?: string; action?: string; result?: string };
type Props = { workspaces?: GovernanceWorkspace[]; members?: GovernanceMember[]; audit?: GovernanceAudit[]; canManageMembers?: boolean; onReload?: () => Promise<void>; compact?: boolean };

export default function GovernancePanel({ workspaces = [], members = [], audit = [], canManageMembers = false, onReload, compact = false }: Props) {
  const [open, setOpen] = useState(false);
  const [message, setMessage] = useState("");
  const [member, setMember] = useState({ member_id: "", workspace_id: workspaces[0]?.workspace_id ?? "personal", role: "reader" });
  const [working, setWorking] = useState("");
  const accessAudit = useMemo(() => audit.filter((item) => ["create_member", "update_member_status", "update_project_status"].includes(item.action ?? "")).slice(-8).reverse(), [audit]);
  const membersFor = (workspaceId: string) => members.filter((item) => item.workspace_id === workspaceId);
  async function submit(event: FormEvent) { event.preventDefault(); if (!canManageMembers || !member.member_id) return; if (!window.confirm(`Confirma o convite do membro “${member.member_id}” no workspace selecionado?`)) return; setWorking("create"); setMessage(""); try { const response = await fetch("/api/control-plane", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "member_create", ...member, confirm: true }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || "Não foi possível criar o convite."); setMessage("Convite criado e auditado."); setMember({ ...member, member_id: "" }); setOpen(false); await onReload?.(); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha ao criar convite."); } finally { setWorking(""); } }
  async function updateStatus(item: GovernanceMember, status: string) { if (!canManageMembers || !window.confirm(`Confirma alterar ${item.member_id} para ${status}?`)) return; setWorking(`${item.member_id}:${status}`); setMessage(""); try { const response = await fetch("/api/control-plane", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "member_status", member_id: item.member_id, workspace_id: item.workspace_id, status, confirm: true }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || "Não foi possível atualizar o membro."); setMessage("Status do membro atualizado e auditado."); await onReload?.(); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha ao atualizar membro."); } finally { setWorking(""); } }
  return <section className={`${styles.panel} ${compact ? styles.compact : ""}`}>
    <div className={styles.heading}><div><p className={styles.kicker}>GOVERNANÇA</p><h2>Membros e workspaces</h2></div><button className={styles.primary} disabled={!canManageMembers} title={!canManageMembers ? "Seu papel permite apenas leitura." : undefined} onClick={() => { setOpen((value) => !value); setMessage(""); }}><Users size={14} /> Novo membro</button></div>
    {message && <p className={styles.message} aria-live="polite">{message}</p>}
    {open && <form className={styles.form} onSubmit={submit}><label>Identificador<input required pattern="[A-Za-z0-9._-]+" value={member.member_id} onChange={(event) => setMember({ ...member, member_id: event.target.value })} placeholder="operador-1" /></label><label>Workspace<select value={member.workspace_id} onChange={(event) => setMember({ ...member, workspace_id: event.target.value })}>{workspaces.map((workspace) => <option key={workspace.workspace_id} value={workspace.workspace_id}>{workspace.name}</option>)}</select></label><label>Papel<select value={member.role} onChange={(event) => setMember({ ...member, role: event.target.value })}><option value="reader">Reader</option><option value="reviewer">Reviewer</option><option value="workspace_admin">Workspace admin</option></select></label><button className={styles.primary} disabled={working === "create" || !canManageMembers} type="submit">{working === "create" ? "Criando…" : "Confirmar convite"}</button></form>}
    <div className={styles.workspaces}>{workspaces.length ? workspaces.map((workspace) => { const checklist = workspace.checklist; return <article className={styles.workspace} key={workspace.workspace_id}><div className={styles.workspaceTitle}><div><strong>{workspace.name}</strong><small>{workspace.workspace_id}{workspace.owner_id ? ` · owner: ${workspace.owner_id}` : ""}</small></div><span className={checklist?.complete ? styles.complete : styles.pending}>{checklist?.complete ? <><CheckCircle2 size={13} /> Completo</> : <><CircleAlert size={13} /> Pendente</>}</span></div><div className={styles.memberList}>{membersFor(workspace.workspace_id).map((item) => <div className={styles.member} key={item.member_id}><div><strong>{item.member_id}</strong><small>{item.role}</small></div><span className={`${styles.status} ${item.status === "active" ? styles.active : item.status === "invited" ? styles.invited : styles.suspended}`}>{item.status}</span>{item.status !== "active" && <button disabled={!canManageMembers || !!working} onClick={() => updateStatus(item, "active")}>{working === `${item.member_id}:active` ? "Ativando…" : "Ativar"}</button>}{item.status === "active" && item.member_id !== "admin" && <button disabled={!canManageMembers || !!working} onClick={() => updateStatus(item, "suspended")}>{working === `${item.member_id}:suspended` ? "Suspendendo…" : "Suspender"}</button>}</div>)}</div></article>; }) : <p className={styles.empty}>Nenhum workspace disponível.</p>}</div>
    {accessAudit.length > 0 && <div className={styles.audit}><div className={styles.auditHeading}><strong>Auditoria de acesso</strong><span>{accessAudit.length} evento(s)</span></div>{accessAudit.map((item, index) => <div className={styles.auditItem} key={`${item.timestamp}-${index}`}><div><strong>{item.action}</strong><small>{item.project_id ?? "sem projeto"} · {item.actor_id ?? "ator não informado"}</small></div><span>{item.result ?? "sem resultado"}</span></div>)}</div>}
  </section>;
}
